{% set name = "hyrise" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - setuptools >=69
    - wheel
  run:
    - python >=3.9,<3.13
    - beautifulsoup4 >=4.12
    - multiqc >=1.33
    - pyyaml >=6.0
    - questionary >=2.0
    - requests >=2.31
    - rich >=13.7
    - tomli >=2.0  # [py<311]

test:
  requires:
    - pip
  commands:
    - hyrise --help
    - python -m hyrise --help
    - hyrise --version
    - pip check

about:
  home: https://github.com/phac-nml/HyRISE
  summary: HIV Resistance Interpretation and Visualization System
  description: |
    HyRISE is a bioinformatics CLI for HIV resistance interpretation and report generation.
    It processes Sierra JSON outputs, supports SierraLocal workflows, and can run with
    container-based execution on HPC environments.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://github.com/phac-nml/HyRISE
  dev_url: https://github.com/phac-nml/HyRISE

extra:
  recipe-maintainers:
    - gosahan
